### ISSUE TITLE
memflow-daemon is not building

### ISSUE THREAD

**Issue by D34Dspy** [memflow/memflow-cli#9]
Crate "memflow-daemon" is not compiling on my end, both branches "main" and "next" produce the same results. Not sure if this is known therefor I've made the issue. The machine for this repo  to be deployed on is gentoo x86-64 with open-rc as init manager. I've previously only made changes to the install script, so it uses the appropiate commands. I first thought memflow-daemon's build.rs is failing at some point however its not refering to any file other than the memflow_rpc.proto which is existing, so I've tried "hacking" with it but I couldn't figure out what appears to be the issue other than a file not being found (judging from compilation output), and no other files were created which suggest any failure. I've attached a file which contains the build log ("$ cargo build --release --all-features --verbose 2<build.log", on next branch). However I've found it to be not helpful, and there was no issue template so I am not sure what you require as a rust developer to acquire relevant information, so feel free to request anything.
[build.log](https://github.com/memflow/memflow-cli/files/8105139/build.log)
Delete this if this is no news :+1:

**Comment by h33p** [comment]
Curious why main branch doesn't compile, but I will probably mark this as wontfix, because a full rewrite is in the works for 0.2
